version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./server/
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb